### ISSUE TITLE
Documentation for the -movie parameter.

### ISSUE THREAD

**Issue by ozbonus** [fx02/cndoom#13]
I'm at a loss at how the -movie parameter is supposed to work. Is it meant to output a video file? It doesn't seem to do anything when I use it and I haven't found anything on the web regarding it.

**Comment by fragglet** [comment]
Maybe this is a cndoom-specific feature but there doesn't seem to be any such parameter in the codebase. Where did you learn that it was supposed to exist?

**Comment by ozbonus** [comment]
It's mentioned in the README and the CMDLIN.doom files. The release (Windows version at least) includes a couple media encoding libraries, too.

Check this out: https://github.com/fx02/cndoom/blob/cndoom/README#L88-L89

**Comment by fragglet** [comment]
Oh! Sorry, I was looking in the wrong place - the parameter does exist. But (and @fx02 can correct me here if I'm wrong) I don't think it does what you think it does. This isn't for generating video files but rather for recording "movie" demos (a type of long Compet-N demo, I'm not sure the exact definition)

**Comment by fx02** [comment]
Yes, fraggle is correct. Movie parameter is for recording movie category **demos** not videos. Comeptition Doom is for COMPET-N/Competition only. Video recording is as far as I know on Chocolate Doom TODO list and I hope we will see it in v3 release :)

**Comment by fragglet** [comment]
Also: you might want to follow along on chocolate-doom/chocolate-doom#715

**Comment by ozbonus** [comment]
Ah, I see. Thanks for clearing that up.
